# Generated by Django 4.2.4 on 2023-08-14 19:49

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("note", "pg_vector"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteFileembedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("created_ts", models.DateTimeField(auto_now_add=True)),
                ("updated_ts", models.DateTimeField(auto_now=True)),
                ("the_file", models.BinaryField()),
                ("date_published", models.DateTimeField(blank=True, null=True)),
                ("publisher", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NoteEmbedding",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_ts", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                ("vector", pgvector.django.VectorField(dimensions=1536, null=True)),
                (
                    "file_embedding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="note.notefileembedding",
                    ),
                ),
            ],
        ),
    ]
