# Generated by Django 4.1.7 on 2023-10-05 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_history_file_uploaded_alter_history_llm_algo_used_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="user_id",
            new_name="user_owner",
        ),
    ]
