# Generated by Django 4.2.4 on 2023-08-18 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("note", "0001_initial"),
        ("chat", "pg_vector"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteEmbedding",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("file_text", models.TextField()),
                ("vector", pgvector.django.VectorField(dimensions=384, null=True)),
                (
                    "file_embedding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="note.notefileembedding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("user_question", models.TextField()),
                ("llm_response", models.TextField()),
                ("response_to_user", models.TextField()),
                ("llm_algo_used", models.TextField()),
                ("embedding_context", models.JSONField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
