# Generated by Django 4.2.4 on 2023-08-16 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_history_embedding_context"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="metadata",
        ),
    ]
