# Generated by Django 4.1.7 on 2023-10-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_rename_user_id_history_user_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="the_file",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
