# Generated by Django 4.1.7 on 2023-10-09 19:44

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_history_the_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noteembedding",
            name="vector",
            field=pgvector.django.VectorField(dimensions=768, null=True),
        ),
    ]
